package types

const ErrorCodeRequired = "required"
const ErrorCodeAlreadyExists = "alreadyExists"
const ErrorCodeInvalid = "invalid"
const ErrorCodeNotExists = "notExists"
const ErrorCodeMustNotBeSet = "mustNotBeSet"
const ErrorCodeMustBeAtLeast = "mustBeAtLeast"
const ErrorCodeMustBeAtMost = "mustBeAtMost"
const ErrorCodeMustBeExactly = "mustBeExactly"
const ErrorCodeInvalidCredentials = "invalidCredentials"
const ErrorCodeExpired = "expired"
const ErrorCodeNotConfirmed = "notConfirmed"
const ErrorCodeAlreadyConfirmed = "alreadyConfirmed"
const ErrorCodeUploadLimitExceeded = "uploadLimitExceeded"
const ErrorCodeImageWidthMustBeAtMost = "imageWidthMustBeAtMost"
const ErrorCodeImageHeightMustBeAtMost = "imageHeightMustBeAtMost"
const ErrorCodeInsufficientPoints = "insufficientPoints"
const ErrorCodeNotActivated = "notActivated"
