package public

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	fog_errors "github.com/friendsofgo/errors"
	"github.com/gofrs/uuid"

	"myvendor.mytld/myproject/backend/api"
	common_helper "myvendor.mytld/myproject/backend/api/graph/common/helper"
	"myvendor.mytld/myproject/backend/api/graph/public/generated"
	"myvendor.mytld/myproject/backend/api/graph/public/helper"
	"myvendor.mytld/myproject/backend/api/graph/public/model"
	"myvendor.mytld/myproject/backend/domain/command"
	"myvendor.mytld/myproject/backend/domain/query"
	"myvendor.mytld/myproject/backend/domain/types"
	"myvendor.mytld/myproject/backend/security/authentication"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, credentials model.LoginCredentials) (*model.LoginResult, error) {
	defer common_helper.ConstantTime(r.SensitiveOperationConstantTime).Wait(ctx)

	cmd := command.NewLoginCmd(credentials.EmailAddress, credentials.Password, credentials.KeepMeLoggedIn)
	var (
		authenticatedAccountID uuid.UUID
		authenticatedRole      types.Role
	)
	cmd.OnAuthenticated = func(accountID uuid.UUID, role types.Role) {
		authenticatedAccountID = accountID
		authenticatedRole = role
	}

	err := r.Handler().Login(ctx, cmd)
	if err != nil {
		if fieldsError := api.FieldsErrorFromErr(err); fieldsError != nil {
			return &model.LoginResult{
				Error: fieldsError,
			}, nil
		}

		return nil, err
	}

	// Build authenticated context to allow fetching account
	ctx = authentication.WithAuthContext(ctx, authentication.AuthContext{
		Authenticated: true,
		Role:          authenticatedRole,
		AccountID:     authenticatedAccountID,
	})
	account, err := r.Finder().QueryAccount(ctx, query.AccountQuery{
		Opts:      helper.AccountQueryOptsFromSelection(ctx, "account"),
		AccountID: authenticatedAccountID,
	})
	if err != nil {
		return nil, fog_errors.Wrap(err, "finding account")
	}

	return &model.LoginResult{
		Account: helper.MapToAccount(account),
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.Error, error) {
	cmd := command.NewAuthSessionLogoutCmd()

	err := r.Handler().AuthSessionLogout(ctx, cmd)
	if err != nil {
		return nil, err
	}

	return nil, nil
}

// LoginStatus is the resolver for the loginStatus field.
func (r *queryResolver) LoginStatus(ctx context.Context) (bool, error) {
	authCtx := authentication.GetAuthContext(ctx)
	return authCtx.Authenticated, nil
}

// CurrentAccount is the resolver for the currentAccount field.
func (r *queryResolver) CurrentAccount(ctx context.Context) (*model.Account, error) {
	authCtx := authentication.GetAuthContext(ctx)
	account, err := r.finder.QueryAccount(ctx, query.AccountQuery{
		AccountID: authCtx.AccountID,
		Opts:      helper.AccountQueryOptsFromSelection(ctx),
	})
	if err != nil {
		return nil, fog_errors.Wrap(err, "finding account")
	}

	return helper.MapToAccount(account), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
