stages:
  - prepare
  - build
  - test
  - docker-build
  - deploy
  - acceptance

default:
  interruptible: true
  retry: 2

include:
  - local: ci/gitlab/**.yml
  - project: "networkteam/gitlab-ci-common"
    file: "/includes/docker-build.yaml"

variables:
  SECURE_ANALYZERS_PREFIX: registry.gitlab.com/gitlab-org/security-products/analyzers
