sonar.projectKey=myproject.backend
sonar.projectName=myproject / Backend

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/*_gen.go,**/*.gen.go,api/graph/generated/**,api/graph/**/*.graphqls,test/fixtures/**,persistence/migrations/**,**/*.yaml,docs/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**

sonar.coverage.exclusions=cli/**/*,persistence/migrations/*.go

sonar.go.coverage.reportPaths=coverage.out
