package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/gofrs/uuid"

	"myvendor.mytld/myproject/backend/api/graph/generated"
	"myvendor.mytld/myproject/backend/api/graph/helper"
	"myvendor.mytld/myproject/backend/api/graph/model"
	domain_model "myvendor.mytld/myproject/backend/domain"
	"myvendor.mytld/myproject/backend/persistence/repository"
)

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, role domain_model.Role, emailAddress string, password string, organisationID *uuid.UUID) (*model.Account, error) {
	cmd, err := domain_model.NewAccountCreateCmd(emailAddress, domain_model.Role(role), password)
	if err != nil {
		return nil, err
	}

	// Only set OrganisationID if the role fits (work around an issue with selecting an organisation and then changing the role in the admin UI)
	if domain_model.Role(role) != domain_model.RoleSystemAdministrator {
		cmd.OrganisationID = helper.ToNullUUID(organisationID)
	}
	err = r.Handler().AccountCreate(ctx, cmd)
	if err != nil {
		return nil, err
	}

	record, err := r.Finder().QueryAccount(ctx, domain_model.AccountQuery{
		AccountID: cmd.AccountID,
	})
	if err != nil {
		return nil, err
	}
	return helper.MapToAccount(record), nil
}

// UpdateAccount is the resolver for the updateAccount field.
func (r *mutationResolver) UpdateAccount(ctx context.Context, id uuid.UUID, role domain_model.Role, emailAddress string, password *string, organisationID *uuid.UUID) (*model.Account, error) {
	// Fetch previous record to get organisation id
	prevRecord, err := r.Finder().QueryAccount(ctx, domain_model.AccountQuery{
		AccountID: id,
	})
	if err != nil {
		return nil, err
	}

	cmd, err := domain_model.NewAccountUpdateCmd(r.Config, prevRecord.OrganisationID, id, emailAddress, role, helper.ToVal(password))
	if err != nil {
		return nil, err
	}
	// Only set NewOrganisationID if the role fits (work around an issue with selecting an organisation and then changing the role in the admin UI)
	if domain_model.Role(role) != domain_model.RoleSystemAdministrator {
		cmd.NewOrganisationID = helper.ToNullUUID(organisationID)
	}
	err = r.Handler().AccountUpdate(ctx, cmd)
	if err != nil {
		return nil, err
	}

	record, err := r.Finder().QueryAccount(ctx, domain_model.AccountQuery{
		AccountID: id,
	})
	if err != nil {
		return nil, err
	}
	return helper.MapToAccount(record), nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, id uuid.UUID) (*model.Account, error) {
	record, err := r.Finder().QueryAccount(ctx, domain_model.AccountQuery{
		AccountID: id,
	})
	if err != nil {
		return nil, err
	}

	cmd := domain_model.NewAccountDeleteCmd(id, record.OrganisationID)
	err = r.Handler().AccountDelete(ctx, cmd)
	if err != nil {
		return nil, err
	}
	return helper.MapToAccount(record), nil
}

// CreateOrganisation is the resolver for the createOrganisation field.
func (r *mutationResolver) CreateOrganisation(ctx context.Context, name string) (*model.Organisation, error) {
	cmd, err := domain_model.NewOrganisationCreateCmd()
	if err != nil {
		return nil, err
	}
	cmd.Name = name
	err = r.Handler().OrganisationCreate(ctx, cmd)
	if err != nil {
		return nil, err
	}
	record, err := r.Finder().QueryOrganisation(ctx, domain_model.OrganisationQuery{
		OrganisationID: cmd.OrganisationID,
	})
	if err != nil {
		return nil, err
	}
	return helper.MapToOrganisation(record), nil
}

// UpdateOrganisation is the resolver for the updateOrganisation field.
func (r *mutationResolver) UpdateOrganisation(ctx context.Context, id uuid.UUID, name string) (*model.Organisation, error) {
	cmd := domain_model.OrganisationUpdateCmd{
		OrganisationID: id,
		Name:           name,
	}
	err := r.Handler().OrganisationUpdate(ctx, cmd)
	if err != nil {
		return nil, err
	}
	record, err := r.Finder().QueryOrganisation(ctx, domain_model.OrganisationQuery{
		OrganisationID: id,
	})
	if err != nil {
		return nil, err
	}
	return helper.MapToOrganisation(record), nil
}

// DeleteOrganisation is the resolver for the deleteOrganisation field.
func (r *mutationResolver) DeleteOrganisation(ctx context.Context, id uuid.UUID) (*model.Organisation, error) {
	record, err := r.Finder().QueryOrganisation(ctx, domain_model.OrganisationQuery{
		OrganisationID: id,
	})
	if err != nil {
		return nil, err
	}

	cmd := domain_model.NewOrganisationDeleteCmd(id)
	err = r.Handler().OrganisationDelete(ctx, cmd)
	if err != nil {
		return nil, err
	}
	return helper.MapToOrganisation(record), nil
}

// Account is the resolver for the Account field.
func (r *queryResolver) Account(ctx context.Context, id uuid.UUID) (*model.Account, error) {
	record, err := r.Finder().QueryAccount(ctx, domain_model.AccountQuery{
		AccountID: id,
	})
	if err == repository.ErrNotFound {
		return nil, nil
	} else if err != nil {
		return nil, err
	}
	return helper.MapToAccount(record), nil
}

// AllAccounts is the resolver for the allAccounts field.
func (r *queryResolver) AllAccounts(ctx context.Context, page *int, perPage *int, sortField *string, sortOrder *string, filter *model.AccountFilter) ([]*model.Account, error) {
	query := helper.MapFromAccountFilter(filter)

	paging, err := helper.MapToPaging(page, perPage, sortField, sortOrder)
	if err != nil {
		return nil, err
	}
	records, err := r.Finder().QueryAccounts(ctx, query, paging)
	if err != nil {
		return nil, err
	}
	return helper.MapToAccounts(records), nil
}

// AllAccountsMeta is the resolver for the _allAccountsMeta field.
func (r *queryResolver) AllAccountsMeta(ctx context.Context, page *int, perPage *int, sortField *string, sortOrder *string, filter *model.AccountFilter) (*model.ListMetadata, error) {
	query := helper.MapFromAccountFilter(filter)
	count, err := r.Finder().CountAccounts(ctx, query)
	if err != nil {
		return nil, err
	}
	return &model.ListMetadata{
		Count: count,
	}, nil
}

// Organisation is the resolver for the Organisation field.
func (r *queryResolver) Organisation(ctx context.Context, id uuid.UUID) (*model.Organisation, error) {
	record, err := r.Finder().QueryOrganisation(ctx, domain_model.OrganisationQuery{
		OrganisationID: id,
	})
	if err == repository.ErrNotFound {
		return nil, nil
	} else if err != nil {
		return nil, err
	}
	return helper.MapToOrganisation(record), nil
}

// AllOrganisations is the resolver for the allOrganisations field.
func (r *queryResolver) AllOrganisations(ctx context.Context, page *int, perPage *int, sortField *string, sortOrder *string, filter *model.OrganisationFilter) ([]*model.Organisation, error) {
	query := helper.MapToOrganisationsQuery(filter)

	paging, err := helper.MapToPaging(page, perPage, sortField, sortOrder)
	if err != nil {
		return nil, err
	}
	records, err := r.Finder().QueryOrganisations(ctx, query, paging)
	if err != nil {
		return nil, err
	}
	return helper.MapToOrganisations(records), nil
}

// AllOrganisationsMeta is the resolver for the _allOrganisationsMeta field.
func (r *queryResolver) AllOrganisationsMeta(ctx context.Context, page *int, perPage *int, sortField *string, sortOrder *string, filter *model.OrganisationFilter) (*model.ListMetadata, error) {
	query := helper.MapToOrganisationsQuery(filter)

	count, err := r.Finder().CountOrganisations(ctx, query)
	if err != nil {
		return nil, err
	}
	return &model.ListMetadata{
		Count: count,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
