package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"myvendor.mytld/myproject/backend/api/graph/generated"
)

// Echo is the resolver for the echo field.
func (r *queryResolver) Echo(ctx context.Context, hello string) (string, error) {
	return fmt.Sprintf("Hello, %s", hello), nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
