// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package asynq_test

import (
	"context"
	"myvendor.mytld/myproject/backend/domain/command"
	"myvendor.mytld/myproject/backend/jobqueue"
	"sync"
)

// Ensure, that CommandHandlerMock does implement jobqueue.CommandHandler.
// If this is not the case, regenerate this file with moq.
var _ jobqueue.CommandHandler = &CommandHandlerMock{}

// CommandHandlerMock is a mock implementation of jobqueue.CommandHandler.
//
//	func TestSomethingThatUsesCommandHandler(t *testing.T) {
//
//		// make and configure a mocked jobqueue.CommandHandler
//		mockedCommandHandler := &CommandHandlerMock{
//			AccountSendWelcomeEmailFunc: func(ctx context.Context, cmd command.AccountSendWelcomeEmail) error {
//				panic("mock out the AccountSendWelcomeEmail method")
//			},
//		}
//
//		// use mockedCommandHandler in code that requires jobqueue.CommandHandler
//		// and then make assertions.
//
//	}
type CommandHandlerMock struct {
	// AccountSendWelcomeEmailFunc mocks the AccountSendWelcomeEmail method.
	AccountSendWelcomeEmailFunc func(ctx context.Context, cmd command.AccountSendWelcomeEmail) error

	// calls tracks calls to the methods.
	calls struct {
		// AccountSendWelcomeEmail holds details about calls to the AccountSendWelcomeEmail method.
		AccountSendWelcomeEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cmd is the cmd argument value.
			Cmd command.AccountSendWelcomeEmail
		}
	}
	lockAccountSendWelcomeEmail sync.RWMutex
}

// AccountSendWelcomeEmail calls AccountSendWelcomeEmailFunc.
func (mock *CommandHandlerMock) AccountSendWelcomeEmail(ctx context.Context, cmd command.AccountSendWelcomeEmail) error {
	callInfo := struct {
		Ctx context.Context
		Cmd command.AccountSendWelcomeEmail
	}{
		Ctx: ctx,
		Cmd: cmd,
	}
	mock.lockAccountSendWelcomeEmail.Lock()
	mock.calls.AccountSendWelcomeEmail = append(mock.calls.AccountSendWelcomeEmail, callInfo)
	mock.lockAccountSendWelcomeEmail.Unlock()
	if mock.AccountSendWelcomeEmailFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.AccountSendWelcomeEmailFunc(ctx, cmd)
}

// AccountSendWelcomeEmailCalls gets all the calls that were made to AccountSendWelcomeEmail.
// Check the length with:
//
//	len(mockedCommandHandler.AccountSendWelcomeEmailCalls())
func (mock *CommandHandlerMock) AccountSendWelcomeEmailCalls() []struct {
	Ctx context.Context
	Cmd command.AccountSendWelcomeEmail
} {
	var calls []struct {
		Ctx context.Context
		Cmd command.AccountSendWelcomeEmail
	}
	mock.lockAccountSendWelcomeEmail.RLock()
	calls = mock.calls.AccountSendWelcomeEmail
	mock.lockAccountSendWelcomeEmail.RUnlock()
	return calls
}
