// Code generated by construct, DO NOT EDIT.
package repository

import (
	uuid "github.com/gofrs/uuid"
	qrb "github.com/networkteam/qrb"
	builder "github.com/networkteam/qrb/builder"
	fn "github.com/networkteam/qrb/fn"
	model "myvendor.mytld/myproject/backend/domain/model"
	types "myvendor.mytld/myproject/backend/domain/types"
	"slices"
	"time"
)

var account = struct {
	builder.Identer
	ID             builder.IdentExp
	EmailAddress   builder.IdentExp
	PasswordHash   builder.IdentExp
	Role           builder.IdentExp
	LastLogin      builder.IdentExp
	OrganisationID builder.IdentExp
	CreatedAt      builder.IdentExp
	UpdatedAt      builder.IdentExp
}{
	CreatedAt:      qrb.N("accounts.created_at"),
	EmailAddress:   qrb.N("accounts.email_address"),
	ID:             qrb.N("accounts.account_id"),
	Identer:        qrb.N("accounts"),
	LastLogin:      qrb.N("accounts.last_login"),
	OrganisationID: qrb.N("accounts.organisation_id"),
	PasswordHash:   qrb.N("accounts.password_hash"),
	Role:           qrb.N("accounts.role_identifier"),
	UpdatedAt:      qrb.N("accounts.updated_at"),
}

var accountSortFields = map[string]builder.IdentExp{
	"createdat":    account.CreatedAt,
	"emailaddress": account.EmailAddress,
	"lastlogin":    account.LastLogin,
	"role":         account.Role,
	"updatedat":    account.UpdatedAt,
}

type AccountChangeSet struct {
	ID             *uuid.UUID
	EmailAddress   *string
	PasswordHash   []byte
	Role           *types.Role
	LastLogin      **time.Time
	OrganisationID *uuid.NullUUID
}

func (c AccountChangeSet) Empty() bool {
	if c.ID != nil {
		return false
	}
	if c.EmailAddress != nil {
		return false
	}
	if c.PasswordHash != nil {
		return false
	}
	if c.Role != nil {
		return false
	}
	if c.LastLogin != nil {
		return false
	}
	if c.OrganisationID != nil {
		return false
	}
	return true
}

func (c AccountChangeSet) toMap() map[string]interface{} {
	m := make(map[string]interface{})
	if c.ID != nil {
		m["account_id"] = *c.ID
	}
	if c.EmailAddress != nil {
		m["email_address"] = *c.EmailAddress
	}
	if c.PasswordHash != nil {
		m["password_hash"] = c.PasswordHash
	}
	if c.Role != nil {
		m["role_identifier"] = *c.Role
	}
	if c.LastLogin != nil {
		m["last_login"] = *c.LastLogin
	}
	if c.OrganisationID != nil {
		m["organisation_id"] = *c.OrganisationID
	}
	return m
}

func AccountToChangeSet(r model.Account) (c AccountChangeSet) {
	if r.ID != uuid.Nil {
		c.ID = &r.ID
	}
	c.EmailAddress = &r.EmailAddress
	c.PasswordHash = r.PasswordHash
	c.Role = &r.Role
	c.LastLogin = &r.LastLogin
	c.OrganisationID = &r.OrganisationID
	return
}

func DiffAccount(source model.Account, target model.Account) (c AccountChangeSet) {
	if source.ID != target.ID {
		c.ID = &target.ID
	}
	if source.EmailAddress != target.EmailAddress {
		c.EmailAddress = &target.EmailAddress
	}
	if !slices.Equal(source.PasswordHash, target.PasswordHash) {
		c.PasswordHash = target.PasswordHash
	}
	if source.Role != target.Role {
		c.Role = &target.Role
	}
	if !((source.LastLogin == nil && target.LastLogin == nil) || (source.LastLogin != nil && target.LastLogin != nil && source.LastLogin.Equal(*target.LastLogin))) {
		c.LastLogin = &target.LastLogin
	}
	if source.OrganisationID != target.OrganisationID {
		c.OrganisationID = &target.OrganisationID
	}
	return c
}

var accountDefaultJson = fn.JsonBuildObject().
	Prop("ID", account.ID).
	Prop("EmailAddress", account.EmailAddress).
	Prop("PasswordHash", qrb.Func("ENCODE", account.PasswordHash, qrb.String("BASE64"))).
	Prop("Role", account.Role).
	Prop("LastLogin", account.LastLogin).
	Prop("OrganisationID", account.OrganisationID).
	Prop("CreatedAt", account.CreatedAt).
	Prop("UpdatedAt", account.UpdatedAt)

var authAccessToken = struct {
	builder.Identer
	ID            builder.IdentExp
	AuthSessionID builder.IdentExp
	ExpiresAt     builder.IdentExp
	CreatedAt     builder.IdentExp
}{
	AuthSessionID: qrb.N("auth_access_tokens.auth_session_id"),
	CreatedAt:     qrb.N("auth_access_tokens.created_at"),
	ExpiresAt:     qrb.N("auth_access_tokens.expires_at"),
	ID:            qrb.N("auth_access_tokens.auth_access_token_id"),
	Identer:       qrb.N("auth_access_tokens"),
}

var authAccessTokenSortFields = map[string]builder.IdentExp{}

type AuthAccessTokenChangeSet struct {
	ID            *uuid.UUID
	AuthSessionID *uuid.UUID
	ExpiresAt     *time.Time
	CreatedAt     *time.Time
}

func (c AuthAccessTokenChangeSet) Empty() bool {
	if c.ID != nil {
		return false
	}
	if c.AuthSessionID != nil {
		return false
	}
	if c.ExpiresAt != nil {
		return false
	}
	if c.CreatedAt != nil {
		return false
	}
	return true
}

func (c AuthAccessTokenChangeSet) toMap() map[string]interface{} {
	m := make(map[string]interface{})
	if c.ID != nil {
		m["auth_access_token_id"] = *c.ID
	}
	if c.AuthSessionID != nil {
		m["auth_session_id"] = *c.AuthSessionID
	}
	if c.ExpiresAt != nil {
		m["expires_at"] = *c.ExpiresAt
	}
	if c.CreatedAt != nil {
		m["created_at"] = *c.CreatedAt
	}
	return m
}

func AuthAccessTokenToChangeSet(r model.AuthAccessToken) (c AuthAccessTokenChangeSet) {
	if r.ID != uuid.Nil {
		c.ID = &r.ID
	}
	if r.AuthSessionID != uuid.Nil {
		c.AuthSessionID = &r.AuthSessionID
	}
	if !r.ExpiresAt.IsZero() {
		c.ExpiresAt = &r.ExpiresAt
	}
	if !r.CreatedAt.IsZero() {
		c.CreatedAt = &r.CreatedAt
	}
	return
}

func DiffAuthAccessToken(source model.AuthAccessToken, target model.AuthAccessToken) (c AuthAccessTokenChangeSet) {
	if source.ID != target.ID {
		c.ID = &target.ID
	}
	if source.AuthSessionID != target.AuthSessionID {
		c.AuthSessionID = &target.AuthSessionID
	}
	if !source.ExpiresAt.Equal(target.ExpiresAt) {
		c.ExpiresAt = &target.ExpiresAt
	}
	if !source.CreatedAt.Equal(target.CreatedAt) {
		c.CreatedAt = &target.CreatedAt
	}
	return c
}

var authAccessTokenDefaultJson = fn.JsonBuildObject().
	Prop("ID", authAccessToken.ID).
	Prop("AuthSessionID", authAccessToken.AuthSessionID).
	Prop("ExpiresAt", authAccessToken.ExpiresAt).
	Prop("CreatedAt", authAccessToken.CreatedAt)

var authSession = struct {
	builder.Identer
	ID         builder.IdentExp
	AccountID  builder.IdentExp
	DeviceInfo builder.IdentExp
	CreatedAt  builder.IdentExp
}{
	AccountID:  qrb.N("auth_sessions.account_id"),
	CreatedAt:  qrb.N("auth_sessions.created_at"),
	DeviceInfo: qrb.N("auth_sessions.device_info"),
	ID:         qrb.N("auth_sessions.auth_session_id"),
	Identer:    qrb.N("auth_sessions"),
}

var authSessionSortFields = map[string]builder.IdentExp{}

type AuthSessionChangeSet struct {
	ID         *uuid.UUID
	AccountID  *uuid.UUID
	DeviceInfo **model.DeviceInfo
	CreatedAt  *time.Time
}

func (c AuthSessionChangeSet) Empty() bool {
	if c.ID != nil {
		return false
	}
	if c.AccountID != nil {
		return false
	}
	if c.DeviceInfo != nil {
		return false
	}
	if c.CreatedAt != nil {
		return false
	}
	return true
}

func (c AuthSessionChangeSet) toMap() map[string]interface{} {
	m := make(map[string]interface{})
	if c.ID != nil {
		m["auth_session_id"] = *c.ID
	}
	if c.AccountID != nil {
		m["account_id"] = *c.AccountID
	}
	if c.DeviceInfo != nil {
		m["device_info"] = *c.DeviceInfo
	}
	if c.CreatedAt != nil {
		m["created_at"] = *c.CreatedAt
	}
	return m
}

func AuthSessionToChangeSet(r model.AuthSession) (c AuthSessionChangeSet) {
	if r.ID != uuid.Nil {
		c.ID = &r.ID
	}
	if r.AccountID != uuid.Nil {
		c.AccountID = &r.AccountID
	}
	c.DeviceInfo = &r.DeviceInfo
	if !r.CreatedAt.IsZero() {
		c.CreatedAt = &r.CreatedAt
	}
	return
}

func DiffAuthSession(source model.AuthSession, target model.AuthSession) (c AuthSessionChangeSet) {
	if source.ID != target.ID {
		c.ID = &target.ID
	}
	if source.AccountID != target.AccountID {
		c.AccountID = &target.AccountID
	}
	if !((source.DeviceInfo == nil && target.DeviceInfo == nil) || (source.DeviceInfo != nil && target.DeviceInfo != nil && source.DeviceInfo.Equal(*target.DeviceInfo))) {
		c.DeviceInfo = &target.DeviceInfo
	}
	if !source.CreatedAt.Equal(target.CreatedAt) {
		c.CreatedAt = &target.CreatedAt
	}
	return c
}

var authSessionDefaultJson = fn.JsonBuildObject().
	Prop("ID", authSession.ID).
	Prop("AccountID", authSession.AccountID).
	Prop("DeviceInfo", authSession.DeviceInfo).
	Prop("CreatedAt", authSession.CreatedAt)

var organisation = struct {
	builder.Identer
	ID        builder.IdentExp
	Name      builder.IdentExp
	CreatedAt builder.IdentExp
	UpdatedAt builder.IdentExp
}{
	CreatedAt: qrb.N("organisations.created_at"),
	ID:        qrb.N("organisations.organisation_id"),
	Identer:   qrb.N("organisations"),
	Name:      qrb.N("organisations.name"),
	UpdatedAt: qrb.N("organisations.updated_at"),
}

var organisationSortFields = map[string]builder.IdentExp{
	"createdat": organisation.CreatedAt,
	"name":      organisation.Name,
	"updatedat": organisation.UpdatedAt,
}

type OrganisationChangeSet struct {
	ID   *uuid.UUID
	Name *string
}

func (c OrganisationChangeSet) Empty() bool {
	if c.ID != nil {
		return false
	}
	if c.Name != nil {
		return false
	}
	return true
}

func (c OrganisationChangeSet) toMap() map[string]interface{} {
	m := make(map[string]interface{})
	if c.ID != nil {
		m["organisation_id"] = *c.ID
	}
	if c.Name != nil {
		m["name"] = *c.Name
	}
	return m
}

func OrganisationToChangeSet(r model.Organisation) (c OrganisationChangeSet) {
	if r.ID != uuid.Nil {
		c.ID = &r.ID
	}
	c.Name = &r.Name
	return
}

func DiffOrganisation(source model.Organisation, target model.Organisation) (c OrganisationChangeSet) {
	if source.ID != target.ID {
		c.ID = &target.ID
	}
	if source.Name != target.Name {
		c.Name = &target.Name
	}
	return c
}

var organisationDefaultJson = fn.JsonBuildObject().
	Prop("ID", organisation.ID).
	Prop("Name", organisation.Name).
	Prop("CreatedAt", organisation.CreatedAt).
	Prop("UpdatedAt", organisation.UpdatedAt)
