// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/gofrs/uuid"

	"myvendor.mytld/myproject/backend/domain/types"
)

type Account struct {
	ID             uuid.UUID  `json:"id"`
	EmailAddress   string     `json:"emailAddress"`
	Role           types.Role `json:"role"`
	LastLogin      *time.Time `json:"lastLogin,omitempty"`
	OrganisationID *uuid.UUID `json:"organisationId,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      time.Time  `json:"updatedAt"`
}

// A generic application error (for expected errors)
type Error struct {
	// An error code that can be translated in the client
	Code string `json:"code"`
	// Arguments for translation of the code
	Arguments []string `json:"arguments"`
}

// A generic field based error
type FieldError struct {
	// A path to the field where the error occured, empty array if the error is not bound to a specific field
	Path []string `json:"path"`
	// An error code that can be translated in the client
	Code string `json:"code"`
	// Arguments for translation of the code
	Arguments []string `json:"arguments"`
}

// An error with information about fields
type FieldsError struct {
	// List of errors specific to a field (or global)
	Errors []*FieldError `json:"errors"`
}

// Login credentials for accounts
type LoginCredentials struct {
	// Email address of the account
	EmailAddress string `json:"emailAddress"`
	// Password of the account
	Password string `json:"password"`
	// Enable longer session
	KeepMeLoggedIn *bool `json:"keepMeLoggedIn,omitempty"`
}

// Login result
type LoginResult struct {
	// The authenticated account (if error is null)
	Account *Account `json:"account,omitempty"`
	// An error if authentication failed
	Error *FieldsError `json:"error,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Result struct {
	// An error if the operation failed
	Error *FieldsError `json:"error,omitempty"`
}
